version: '3.9'

services:
  prereqs:
    image: geometry/protobuilder:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./docker/protobuilder/Dockerfile
    deploy:
      replicas: 0
  areaserver:
    build:
      context: ./
      dockerfile: ./docker/areaserver/Dockerfile
    image: geometry/server:${TAG:-latest}
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
  areaclient:
    # only gurantees the start order (clients can still start before the server)
    depends_on:
      - areaserver
    build:
      context: ./
      dockerfile: ./docker/areaclient/Dockerfile
    image: geometry/client:${TAG:-latest}
    deploy:
      mode: replicated
      replicas: 6
