version: "3.8"

services:
  chstructingest-1:
    image: chstructingest
    container_name: chstructingest-1
    build:
      context: .
      dockerfile: ./Dockerfile
  clickhouse-server-1:
    image: "yandex/clickhouse-server:latest"
    container_name: clickhouse-server-1
    ports:
      - 8123:8123 # http port
      - 9000:9000 # native port
      - 9009:9009 #
