version: '3.4'

services:
  guageappx:
    container_name: guageappx
    image: guageappx
    command: ./guageavg -buckets 60 -interval 5
    build:
      context: .
      dockerfile: ./Dockerfile
  guageappx-help:
    container_name: guageappx-help
    image: guageappx
    command: ./guageavg -h
    build:
      context: .
      dockerfile: ./Dockerfile
