// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgqueries

type Student struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Age  int32  `json:"age"`
}

type TestScore struct {
	StudentID int64  `json:"student_id"`
	Score     int32  `json:"score"`
	Grade     string `json:"grade"`
}
